// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBuyer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInfo      *BaseInfo              `protobuf:"bytes,2,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBuyer) Reset() {
	*x = AccountBuyer{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBuyer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBuyer) ProtoMessage() {}

func (x *AccountBuyer) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBuyer.ProtoReflect.Descriptor instead.
func (*AccountBuyer) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBuyer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountBuyer) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

type AccountSeller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInfo      *BaseInfo              `protobuf:"bytes,2,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	StoreName     string                 `protobuf:"bytes,3,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSeller) Reset() {
	*x = AccountSeller{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSeller) ProtoMessage() {}

func (x *AccountSeller) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSeller.ProtoReflect.Descriptor instead.
func (*AccountSeller) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountSeller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountSeller) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *AccountSeller) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *BaseInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BaseInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BaseInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BaseInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PostAccountBuyerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInfo      *BaseInfo              `protobuf:"bytes,2,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAccountBuyerRequest) Reset() {
	*x = PostAccountBuyerRequest{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAccountBuyerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAccountBuyerRequest) ProtoMessage() {}

func (x *PostAccountBuyerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAccountBuyerRequest.ProtoReflect.Descriptor instead.
func (*PostAccountBuyerRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *PostAccountBuyerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostAccountBuyerRequest) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

type PostAccountBuyerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountBuyer          `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAccountBuyerResponse) Reset() {
	*x = PostAccountBuyerResponse{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAccountBuyerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAccountBuyerResponse) ProtoMessage() {}

func (x *PostAccountBuyerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAccountBuyerResponse.ProtoReflect.Descriptor instead.
func (*PostAccountBuyerResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *PostAccountBuyerResponse) GetAccount() *AccountBuyer {
	if x != nil {
		return x.Account
	}
	return nil
}

type PostAccountSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInfo      *BaseInfo              `protobuf:"bytes,2,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	StoreName     string                 `protobuf:"bytes,3,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAccountSellerRequest) Reset() {
	*x = PostAccountSellerRequest{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAccountSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAccountSellerRequest) ProtoMessage() {}

func (x *PostAccountSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAccountSellerRequest.ProtoReflect.Descriptor instead.
func (*PostAccountSellerRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *PostAccountSellerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostAccountSellerRequest) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *PostAccountSellerRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

type PostAccountSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountSeller         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAccountSellerResponse) Reset() {
	*x = PostAccountSellerResponse{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAccountSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAccountSellerResponse) ProtoMessage() {}

func (x *PostAccountSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAccountSellerResponse.ProtoReflect.Descriptor instead.
func (*PostAccountSellerResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *PostAccountSellerResponse) GetAccount() *AccountSeller {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountSeller         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSellerResponse) Reset() {
	*x = GetAccountSellerResponse{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSellerResponse) ProtoMessage() {}

func (x *GetAccountSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSellerResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSellerResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountSellerResponse) GetAccount() *AccountSeller {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountSellersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSellersRequest) Reset() {
	*x = GetAccountSellersRequest{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSellersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSellersRequest) ProtoMessage() {}

func (x *GetAccountSellersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSellersRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSellersRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountSellersRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetAccountSellersRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetAccountSellersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetAccountSellersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountSeller       `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSellersResponse) Reset() {
	*x = GetAccountSellersResponse{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSellersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSellersResponse) ProtoMessage() {}

func (x *GetAccountSellersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSellersResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSellersResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountSellersResponse) GetAccounts() []*AccountSeller {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x05proto\"L\n" +
	"\fAccountBuyer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\tbase_info\x18\x02 \x01(\v2\x0f.proto.BaseInfoR\bbaseInfo\"l\n" +
	"\rAccountSeller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\tbase_info\x18\x02 \x01(\v2\x0f.proto.BaseInfoR\bbaseInfo\x12\x1d\n" +
	"\n" +
	"store_name\x18\x03 \x01(\tR\tstoreName\"v\n" +
	"\bBaseInfo\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"W\n" +
	"\x17PostAccountBuyerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\tbase_info\x18\x02 \x01(\v2\x0f.proto.BaseInfoR\bbaseInfo\"I\n" +
	"\x18PostAccountBuyerResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.proto.AccountBuyerR\aaccount\"w\n" +
	"\x18PostAccountSellerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\tbase_info\x18\x02 \x01(\v2\x0f.proto.BaseInfoR\bbaseInfo\x12\x1d\n" +
	"\n" +
	"store_name\x18\x03 \x01(\tR\tstoreName\"K\n" +
	"\x19PostAccountSellerResponse\x12.\n" +
	"\aaccount\x18\x01 \x01(\v2\x14.proto.AccountSellerR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x18GetAccountSellerResponse\x12.\n" +
	"\aaccount\x18\x01 \x01(\v2\x14.proto.AccountSellerR\aaccount\"T\n" +
	"\x18GetAccountSellersRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"M\n" +
	"\x19GetAccountSellersResponse\x120\n" +
	"\baccounts\x18\x01 \x03(\v2\x14.proto.AccountSellerR\baccounts2\xac\x04\n" +
	"\x0eAccountService\x12U\n" +
	"\x10PostAccountBuyer\x12\x1e.proto.PostAccountBuyerRequest\x1a\x1f.proto.PostAccountBuyerResponse\"\x00\x12X\n" +
	"\x11PostAccountSeller\x12\x1f.proto.PostAccountSellerRequest\x1a .proto.PostAccountSellerResponse\"\x00\x12C\n" +
	"\x13UpdateAccountSeller\x12\x14.proto.AccountSeller\x1a\x14.proto.AccountSeller\"\x00\x12@\n" +
	"\x12UpdateAccountBuyer\x12\x13.proto.AccountBuyer\x1a\x13.proto.AccountBuyer\"\x00\x12B\n" +
	"\x0fGetAccountBuyer\x12\x18.proto.GetAccountRequest\x1a\x13.proto.AccountBuyer\"\x00\x12D\n" +
	"\x10GetAccountSeller\x12\x18.proto.GetAccountRequest\x1a\x14.proto.AccountSeller\"\x00\x12X\n" +
	"\x11GetAccountSellers\x12\x1f.proto.GetAccountSellersRequest\x1a .proto.GetAccountSellersResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_account_proto_goTypes = []any{
	(*AccountBuyer)(nil),              // 0: proto.AccountBuyer
	(*AccountSeller)(nil),             // 1: proto.AccountSeller
	(*BaseInfo)(nil),                  // 2: proto.BaseInfo
	(*PostAccountBuyerRequest)(nil),   // 3: proto.PostAccountBuyerRequest
	(*PostAccountBuyerResponse)(nil),  // 4: proto.PostAccountBuyerResponse
	(*PostAccountSellerRequest)(nil),  // 5: proto.PostAccountSellerRequest
	(*PostAccountSellerResponse)(nil), // 6: proto.PostAccountSellerResponse
	(*GetAccountRequest)(nil),         // 7: proto.GetAccountRequest
	(*GetAccountSellerResponse)(nil),  // 8: proto.GetAccountSellerResponse
	(*GetAccountSellersRequest)(nil),  // 9: proto.GetAccountSellersRequest
	(*GetAccountSellersResponse)(nil), // 10: proto.GetAccountSellersResponse
}
var file_account_proto_depIdxs = []int32{
	2,  // 0: proto.AccountBuyer.base_info:type_name -> proto.BaseInfo
	2,  // 1: proto.AccountSeller.base_info:type_name -> proto.BaseInfo
	2,  // 2: proto.PostAccountBuyerRequest.base_info:type_name -> proto.BaseInfo
	0,  // 3: proto.PostAccountBuyerResponse.account:type_name -> proto.AccountBuyer
	2,  // 4: proto.PostAccountSellerRequest.base_info:type_name -> proto.BaseInfo
	1,  // 5: proto.PostAccountSellerResponse.account:type_name -> proto.AccountSeller
	1,  // 6: proto.GetAccountSellerResponse.account:type_name -> proto.AccountSeller
	1,  // 7: proto.GetAccountSellersResponse.accounts:type_name -> proto.AccountSeller
	3,  // 8: proto.AccountService.PostAccountBuyer:input_type -> proto.PostAccountBuyerRequest
	5,  // 9: proto.AccountService.PostAccountSeller:input_type -> proto.PostAccountSellerRequest
	1,  // 10: proto.AccountService.UpdateAccountSeller:input_type -> proto.AccountSeller
	0,  // 11: proto.AccountService.UpdateAccountBuyer:input_type -> proto.AccountBuyer
	7,  // 12: proto.AccountService.GetAccountBuyer:input_type -> proto.GetAccountRequest
	7,  // 13: proto.AccountService.GetAccountSeller:input_type -> proto.GetAccountRequest
	9,  // 14: proto.AccountService.GetAccountSellers:input_type -> proto.GetAccountSellersRequest
	4,  // 15: proto.AccountService.PostAccountBuyer:output_type -> proto.PostAccountBuyerResponse
	6,  // 16: proto.AccountService.PostAccountSeller:output_type -> proto.PostAccountSellerResponse
	1,  // 17: proto.AccountService.UpdateAccountSeller:output_type -> proto.AccountSeller
	0,  // 18: proto.AccountService.UpdateAccountBuyer:output_type -> proto.AccountBuyer
	0,  // 19: proto.AccountService.GetAccountBuyer:output_type -> proto.AccountBuyer
	1,  // 20: proto.AccountService.GetAccountSeller:output_type -> proto.AccountSeller
	10, // 21: proto.AccountService.GetAccountSellers:output_type -> proto.GetAccountSellersResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
