CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(27) PRIMARY KEY,
    email VARCHAR(127) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role INT NOT NULLs,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);